#!/bin/bash
# PreToolUse hook: block Edit/Write on uv.lock (auto-generated by uv sync).
set -euo pipefail

FILE=$(cat | jq -r '.tool_input.file_path // empty')

if [[ "$FILE" == */uv.lock || "$FILE" == uv.lock ]]; then
    echo "Blocked: uv.lock is auto-generated by uv sync — do not edit directly" >&2
    exit 2
fi

exit 0
