"""Public API for shardyfusion."""

from ._rate_limiter import (
    AcquireResult,
    RateLimiter,
    ThreadSafeTokenBucket,
    TokenBucket,
)
from .async_manifest_store import (
    AsyncManifestStore,
    AsyncS3ManifestStore,
)
from .cel import CelColumn, CelType, cel_sharding, cel_sharding_by_columns
from .config import (
    BaseShardedWriteConfig,
    BufferingOptions,
    CelShardedWriteConfig,
    CelShardingConfig,
    ColumnWriteInput,
    DaskWriteOptions,
    HashShardedWriteConfig,
    HashShardingConfig,
    KeyValueWriteConfig,
    KvWriteRateLimitConfig,
    PythonRecordInput,
    PythonWriteOptions,
    RayWriteOptions,
    SharedMemoryOptions,
    SingleDbWriteConfig,
    SingleDbWriteOptions,
    SparkWriteOptions,
    UnifiedVectorWriteConfig,
    VectorColumnInput,
    VectorSpec,
    VectorWriteRateLimitConfig,
    WriterLifecycleConfig,
    WriterManifestConfig,
    WriterObservabilityConfig,
    WriterOutputConfig,
    WriterRetryConfig,
    WriterStorageConfig,
)
from .credentials import (
    CredentialProvider,
    EnvCredentialProvider,
    S3Credentials,
    StaticCredentialProvider,
)
from .errors import (
    ConfigValidationError,
    DbAdapterError,
    ManifestBuildError,
    ManifestParseError,
    ManifestStoreError,
    PoolExhaustedError,
    PublishCurrentError,
    PublishManifestError,
    ReaderStateError,
    S3TransientError,
    ShardAssignmentError,
    ShardCoverageError,
    ShardWriteError,
    ShardyfusionError,
)
from .logging import (
    FailureSeverity,
    JsonFormatter,
    LogContext,
    configure_logging,
    get_logger,
)
from .manifest import (
    SQLITE_MANIFEST_CONTENT_TYPE,
    BuildDurations,
    BuildResult,
    BuildStats,
    CurrentPointer,
    ManifestArtifact,
    ManifestRef,
    ManifestShardingSpec,
    ParsedManifest,
    RequiredBuildMeta,
    RequiredShardMeta,
    SqliteManifestBuilder,
    WriterInfo,
)
from .manifest_store import (
    InMemoryManifestStore,
    ManifestStore,
    S3ManifestStore,
    SqliteShardLookup,
    load_sqlite_build_meta,
    parse_manifest_payload,
    parse_sqlite_manifest,
)
from .metrics import MetricEvent, MetricsCollector
from .reader import (
    AsyncShardedReader,
    AsyncShardReaderHandle,
    AsyncSlateDbReaderFactory,
    ConcurrentShardedReader,
    ReaderHealth,
    ShardDetail,
    ShardedReader,
    ShardReaderHandle,
    SlateDbReaderFactory,
    SnapshotInfo,
)
from .routing import ShardLookup, SnapshotRouter
from .run_registry import (
    InMemoryRunRegistry,
    RunRecord,
    RunRecordLifecycle,
    RunRegistry,
    RunStatus,
    S3RunRegistry,
)
from .serde import ValueSpec
from .sharding_types import (
    CelShardingSpec,
    HashShardingSpec,
    KeyEncoding,
    ShardHashAlgorithm,
    ShardingSpec,
    ShardingStrategy,
)
from .slatedb_adapter import (
    DbAdapter,
    DbAdapterFactory,
    SlateDbFactory,
)
from .type_defs import (
    AsyncShardReader,
    AsyncShardReaderFactory,
    RetryConfig,
    S3ConnectionOptions,
    ShardReader,
    ShardReaderFactory,
)

__all__ = [
    "AcquireResult",
    "AsyncManifestStore",
    "AsyncS3ManifestStore",
    "AsyncShardReader",
    "AsyncShardReaderFactory",
    "AsyncShardReaderHandle",
    "AsyncShardedReader",
    "AsyncSlateDbReaderFactory",
    "AsyncUnifiedShardedReader",
    "BuildDurations",
    "BuildResult",
    "BuildStats",
    "BufferingOptions",
    "CelColumn",
    "CelShardingConfig",
    "CelShardingSpec",
    "CelType",
    "CelShardedWriteConfig",
    "ColumnWriteInput",
    "ConcurrentShardedReader",
    "ConfigValidationError",
    "CredentialProvider",
    "DbAdapterError",
    "CurrentPointer",
    "DbAdapter",
    "DbAdapterFactory",
    "DaskWriteOptions",
    "EnvCredentialProvider",
    "FailureSeverity",
    "InMemoryManifestStore",
    "InMemoryRunRegistry",
    "HashShardingConfig",
    "HashShardingSpec",
    "HashShardedWriteConfig",
    "JsonFormatter",
    "KeyEncoding",
    "KeyValueWriteConfig",
    "KvWriteRateLimitConfig",
    "LogContext",
    "ManifestArtifact",
    "ManifestBuildError",
    "WriterManifestConfig",
    "ManifestParseError",
    "ManifestRef",
    "ManifestShardingSpec",
    "ManifestStore",
    "ManifestStoreError",
    "MetricEvent",
    "MetricsCollector",
    "WriterOutputConfig",
    "ParsedManifest",
    "PoolExhaustedError",
    "PublishCurrentError",
    "PublishManifestError",
    "PythonRecordInput",
    "PythonWriteOptions",
    "RayWriteOptions",
    "RateLimiter",
    "ReaderHealth",
    "ReaderStateError",
    "RequiredBuildMeta",
    "RequiredShardMeta",
    "RetryConfig",
    "RunRecord",
    "RunRecordLifecycle",
    "RunRegistry",
    "RunStatus",
    "S3ConnectionOptions",
    "S3Credentials",
    "SQLITE_MANIFEST_CONTENT_TYPE",
    "S3ManifestStore",
    "S3RunRegistry",
    "S3TransientError",
    "ShardAssignmentError",
    "ShardCoverageError",
    "ShardWriteError",
    "ShardDetail",
    "ShardHashAlgorithm",
    "ShardReader",
    "ShardReaderFactory",
    "ShardReaderHandle",
    "ShardedReader",
    "ShardingSpec",
    "ShardLookup",
    "ShardingStrategy",
    "ShardyfusionError",
    "SlateDbFactory",
    "SlateDbReaderFactory",
    "SnapshotInfo",
    "SnapshotRouter",
    "SqliteManifestBuilder",
    "SqliteShardLookup",
    "StaticCredentialProvider",
    "SharedMemoryOptions",
    "SingleDbWriteConfig",
    "SingleDbWriteOptions",
    "SparkWriteOptions",
    "ThreadSafeTokenBucket",
    "TokenBucket",
    "UnifiedShardedReader",
    "UnifiedVectorWriteConfig",
    "ValueSpec",
    "VectorColumnInput",
    "VectorSpec",
    "VectorWriteRateLimitConfig",
    "BaseShardedWriteConfig",
    "WriterLifecycleConfig",
    "WriterObservabilityConfig",
    "WriterInfo",
    "WriterRetryConfig",
    "WriterStorageConfig",
    "cel_sharding",
    "cel_sharding_by_columns",
    "configure_logging",
    "get_logger",
    "load_sqlite_build_meta",
    "parse_manifest_payload",
    "parse_sqlite_manifest",
]


def __getattr__(name: str):  # noqa: ANN202
    if name == "UnifiedShardedReader":
        from .reader.unified_reader import UnifiedShardedReader

        return UnifiedShardedReader
    if name == "AsyncUnifiedShardedReader":
        from .reader.async_unified_reader import AsyncUnifiedShardedReader

        return AsyncUnifiedShardedReader
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
